### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Shyponps** [HipGraph/GNNShap#1]
note that code in "GNNShap-main\baselines\methods\OrphicX\causaleffect.py" .  the function beta_info_flow has two returns . seems that author paste the code in function"joint_uncond" into it accidentally.

**Comment by seakkas** [comment]
We follow the original repository for the 'beta_info_flow' function: https://github.com/WanyuGroup/CVPR2022-OrphicX/blob/main/causalfect.py. It was like this in the original repo.
